project:
  type: book

book:
  title: "Tools-in-Action"
  author: "Kincayde Adkins"
  chapters:
    - index.qmd
    - 01_git.qmd
    - 02_linux_basics.qmd
    - 03_shell_essentials.qmd
    - 04_makefile.qmd
    - 05_sql_sqlite.qmd
    - 06_pandas_joins_parquet.qmd
    - 07_html_scraping.qmd
    - 08_pytest.qmd
    - 09_pytorch_miniloop.qmd
    - 10_quarto_book.qmd
execute:
  echo: true
  freeze: auto